# Generated by Django 3.2 on 2021-05-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_User',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Area_Name', models.CharField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Requests_Remaining', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Medicinal_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.CharField(default='', max_length=70)),
                ('Expiry_Date', models.DateField()),
                ('Quantity', models.IntegerField(default=1)),
                ('General_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medshare.general_user')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.IntegerField(choices=[(-2, 'Unsuccessful'), (-1, 'Rejected'), (0, 'Pending'), (1, 'Accepted'), (2, 'Successful')], default=0)),
                ('Quantity', models.IntegerField(default=1)),
                ('Donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Donator', to='medshare.general_user')),
                ('Medicinal_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medshare.medicinal_product')),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='medshare.general_user')),
            ],
        ),
    ]
